name: Update Tailscale DERP Rules

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggers

jobs:
  update-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Rules
        run: |
          python3 generate_derp.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tailscale-domain.yaml tailscale-ip.yaml
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update Tailscale DERP rules"
            git push
          fi
